apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-gateway-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/borisjaison/devopstrain2025_rollout.git
    targetRevision: HEAD
    path: payment-gateway
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
